### ISSUE TITLE
Allow configuration parameters to be set in files

### ISSUE THREAD

**Issue by vktec** [blogc/blogc#5]
At the moment, all global configuration must be specified on the command line. This works fine for relatively small things, but when you start wanting to store site information, contact information and more in global variables so that they can be easily changed and reused, it becomes a bit tedious.

Adding an option to specify a file with a format similar to that of the headers of source files would be excellent, as it would allow global variables to be stored in their own, separate file and not directly in a Makefile. Comments would also be relatively easy to implement, and would be very useful for organising information.

Here's an example of what such a file could look like:

```yaml
# Site info
SITE_NAME: My awesome blog
SITE_SUMMARY: An awesome blog about awesome stuff, written by an awesome person
SITE_DOMAIN: blog.awesomeguy.com

# Contact/social media
TWITTER: @awesometweeter
GITHUB: @awesomecoder
EMAIL: me@awesomeguy.com
```

Of course, `#` doesn't necessarily need to be used as the comment character, but it would make things easier for those who use editors that already have syntax highlighting support for similar languages such as YAML.
